name: Loadmill Test Run

on:
  push:
    branches:
      - main

jobs:
  loadmill-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Loadmill CLI from GitHub
        run: npm install -g loadmill/loadmill-cli

      - name: Run Loadmill Test Plan

        run: loadmill d90b3e55-1054-4ef7-885f-399f411e147b --test-plan -w -t iKDmpFveDlE0RR8mGIiniXlankIigmsXqekCeSmW
