name: Loadmill Test Run

on:
  push:
    branches:
      - main

jobs:
  loadmill-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Loadmill Test Plan
        run: npx loadmill 351be1b3-b66f-4dbf-820d-5533758d6bf1 --test-plan -w -t lmANYb8JT4NrvqXMpHGwABBPT0bxUsMTQ6LLvsKg
